python_binary(
    name='hello-server-bin',
    dependencies = [
        'src/main/python/hello',
    ],
    source='main.py',
    # No need to set compatibility if it matches the default interpreter constraints.
    #compatibility='CPython>=2.7,<3',
)