python_binary(
    name='hello',
    dependencies = [
        "3rdparty/python:grpcio"
    ],
    source='main.py',
    # No need to set compatibility if it matches the default interpreter constraints.
    #compatibility='CPython>=2.7,<3',
)